# Generated by Django 2.1.13 on 2019-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('车辆编号', models.IntegerField(primary_key=True, serialize=False)),
                ('soc值', models.FloatField(blank=True, db_column='SOC值', null=True)),
                ('soh值', models.FloatField(blank=True, db_column='SOH值', null=True)),
                ('起始位置', models.CharField(blank=True, max_length=1, null=True)),
                ('目的位置', models.CharField(blank=True, max_length=1, null=True)),
                ('充电到达充电桩编号', models.IntegerField(blank=True, null=True)),
                ('开始行使时间', models.TimeField(blank=True, null=True)),
                ('结束行使时间', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chargingstation',
            fields=[
                ('充电站编号', models.IntegerField(primary_key=True, serialize=False)),
                ('经度', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('纬度', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'chargingstation',
                'managed': False,
            },
        ),
    ]
